<entry type="method" name="raises">
  <signature>
    <argument name="block" type="Function">
      <desc>Function to execute</desc>
    </argument>
    <argument name="expected" type="Error">
      <desc>Error Object to compare</desc>
    </argument>
    <argument name="message" type="String">
      <desc>A short description of the assertion</desc>
    </argument>
  </signature>
  <desc>
    Assertion to test if a callback throws an exception when run.
  </desc>
  <longdesc>
    <p>When testing code that is expected to throw an exception based on a specific set of circumstances, use <code>raises()</code> to catch the error object for testing and comparison.</p>
  </longdesc>
  <example height="250">
    <desc>Assert the correct error message is received for a custom error object.</desc>
<code><![CDATA[
test( "raises", function() {

  function CustomError( message ) {
    this.message = message;
  }

  CustomError.prototype.toString = function() {
    return this.message;
  };

  raises(
    function() {
      throw "error"
    },
    "raises with just a message, no expected"
  );

  raises(
    function() {
      throw new CustomError();
    },
    CustomError,
    "raised error is an instance of CustomError"
  );

  raises(
    function() {
      throw new CustomError("some error description");
    },
    /description/,
    "raised error message contains 'description'"
  );
});
]]></code>
  </example>

  <category slug="assert"/>
</entry>
